### ISSUE TITLE
HTML File does not refresh view

### ISSUE THREAD

**Issue by destinatis** [qualialabs/reval#11] opened 2017-06-05 02:59 UTC
Happens occasionally. I think it has to do with moving around the templates.

**Comment by veered** [comment] 2017-06-05 03:13
Could you give more specific steps to reproduce?

**Comment by destinatis** [comment] 2017-06-05 03:30
I don't have the steps. I thought it was cutting and pasting the templates but it is not. I see events in terminal but the view does not refresh.

**Comment by veered** [comment] 2017-06-05 03:51
Are there any errors in the console (browser or server)?

**Comment by destinatis** [comment] 2017-06-05 03:55
http://nebulon.s3.amazonaws.com/snnRMJUU.png

**Comment by veered** [comment] 2017-06-05 04:17
Hmm, I'd guess it's unrelated. Does the editing work for any HTML templates? Does it work for JS?

**Comment by destinatis** [comment] 2017-06-05 04:48
It works for CSS. Can update styles fine? Not HTML tho.

**Comment by destinatis** [comment] 2017-06-05 05:08
Just plain weird.
https://s3.amazonaws.com/nebulon/file-1496639233.mov

**Comment by destinatis** [comment] 2017-06-05 06:37
Noticed, when you type inside templates it works. Just does not work in the body.

**Comment by veered** [comment] 2017-06-05 18:51
Oh, I think the issue is probably just with the `<body>` tag. I'm not surprised that doesn't work. I'll look into it over the weekend. It should work with all named templates. Are you having issues with any named templates (i.e. not the `<body>` tag)?

**Comment by destinatis** [comment] 2017-06-05 19:28
If I typed basic text then you are correct it only works in the templates html and not body. Need to try to o nested templates to see how it goes. On another note, Reval rocks! :P

**Comment by veered** [comment] 2017-06-05 19:50
Thanks :)

I have a good idea of what's going on, I'll let you know when I fix it. In the meantime, if you break out your code into sub templates (so it's not in `<body>`), then you shouldn't have any issues.

**Comment by destinatis** [comment] 2017-06-06 02:03
Right on! Thanks again.

**Comment by destinatis** [comment] 2017-06-06 04:46
BTW, are you able to share a sample project that has a couple of views and some buttons?

**Comment by destinatis** [comment] 2017-06-06 05:47
Also, I can't figure out how to edit multiple html files/js files.

**Comment by veered** [comment] 2017-06-06 17:12
I can try to put together a sample project, shouldn't be very hard.

What do you mean that you can't edit multiple files?

**Comment by destinatis** [comment] 2017-06-06 19:24
Here is an example tree. I want to edit templates in forms.html. 

http://nebulon.s3.amazonaws.com/TMw46ajG.png

The file is imported via main.js but I don't know where to edit it.
I can only edit main.html, main.css and main.js.

Cheers!

**Comment by veered** [comment] 2017-06-10 21:56
I looked into reloading the `<body>` tag, and the prospects don't look good. It works totally different than other templates. The best solution is just to move the code to a sub-template. I've added a warning with this advice.

If you can't find the template you want to edit by clicking it on the page, I recommend using the "Find a template..." search bar.

I'm going to close this issue now.

**Closed by veered** 2017-06-10 21:56 UTC
